---
- hosts: all
  vars_files:
    - vars.yml
  sudo: true
  sudo_user: root

  tasks:  
    - name: clone project repo in destination
      git: repo={{ project_repo }} dest={{ project_root }} accept_hostkey=true
      
    - name: install npm
      npm: path=/var/projects/example
      
    - name: Start Redis
      service: name=redis-server state=started
      
    
   
